### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by thercast** [firesidelabs/fireside-features#11]
I believe it has been mentioned that it was in the roadmap to have an API exposed, but I thought it would be helpful to log it here.  My use case would be to obtain metrics as well as automate the way I upload new episodes so I can basically script out my entire process of publishing content.

**Comment by dan** [comment]
I've never indicated that there would be an API for stats, but there will one day be an API, hopefully in 2018.

**Comment by jm** [comment]
This would be useful to me, also, for the same reasons (automation).  Heck, even if it were just read-only, or even if some of the extra episode information (e.g., header image) were exposed in a `_fireside` key in the JSON feed.  I'm just trying to create a single source of truth about episode data. 😄

**Comment by dan** [comment]
@jm Would the JSON feed work for you, it's been there for quite a while now.

yourpodcast.fireside.fm/json

**Comment by road2one** [comment]
we need an API, or add the header images to the json and RSS feed

**Comment by rpodcast** [comment]
> but there will one day be an API, hopefully in 2018.

Any update on a potential API?  Again I'm mostly interested in being able to publish a new episode with it.  I have a few pipelines I am close to completing but this is the last major piece.

**Comment by ironicbadger** [comment]
Hi, repeating the same question. Is the API ever likely to happen please? :)

Use case is publish episodes via CI.

**Comment by sebastiangelotte** [comment]
Also interested in an API, mainly for publishing new episodes.

**Comment by rezelute** [comment]
We are also in need of this. I need to be able to request the podcast information that was already entered on the site. Currently we have a duplicate of all the information (title, summary , description, transcript etc.) on our site and then on yours. Ideally, it would be hosted only on Fireside only and we should be able to pull this information by episode ID.

**Comment by ironicbadger** [comment]
@dan closing this link to the JSON api is not a complete solution to the request here.

An API that permits publishing and programmatically inserting links from custom tooling would be a great start. But that would just be the beginning really.

Another example, I want to build a searchable archive of all the show notes for half a dozen podcasts. I've had to resort to iterating over the HTML in Python using BeautifulSoup4 - it's so wonderfully hacky and works "OK" but being able to query the information entered into fireside with key/values instead of large blocks would be waaaaay better.

Hopefully you will see this and reconsider.
