### ISSUE TITLE
Email reminder when episode publication date passes and episode is not public

### ISSUE THREAD

**Issue by mfessler** [firesidelabs/fireside-features#25]
Would it be possible to (optionally) have Fireside email the account holder if the publication date passes on a podcast episode, and the episode is still private or unlisted? 

I bet you can guess why I'm requesting this.

**Comment by jonathanbloom** [comment]
This has happened to me twice! 😥

**Comment by dan** [comment]
I cannot guess why, actually.

Dates are used primarily for two purposes in Fireside:

1. To tell Fireside when to publish an episode (for a date in the future)
2. To control sort order

Otherwise, dates "don't matter" to Fireside, and further, there's nothing _wrong_ with having an episode that is private/unlisted with a date in the past. This is by design.

If you're asking for a different kind of behavior around dates, I'd be curious to learn about it, but we won't be sending emails for a condition that is both normal and not indicative of an error.

**Comment by mfessler** [comment]
The scenario in my case is that I will set a publication date for an episode, leave it private or unlisted while I finish show notes or ask for a guest's feedback on the preview page, and then sometimes forget to switch it to public before the publication date. It would be helpful to be able to opt into a reminder email in cases like this. (Maybe it could be a checkbox next to the status and data fields).

**Comment by dan** [comment]
Interesting suggestions, thanks.
